### ISSUE TITLE
need to hide only  force stop button

### ISSUE THREAD

**Issue by arpitjoshi08** [prashantadesara/DeviceAdminDemo#1]
hello sir according to my need i want to disable only force stop button for particular app ..and uninstall button will be enable ..is it possible plzz elaborate ?

**Comment by prashantadesara** [comment]
@arpitjoshi08 : Not its not possible due to Google Security reason.

**Comment by arpitjoshi08** [comment]
okkk thanks for save my time....i was finding  since morning .....

**Comment by arpitjoshi08** [comment]
okk thanks...for save my time......
